### ISSUE TITLE
Add C++

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#1]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by OmKhare** [comment]
Hey I am interested in doing this project. Can you approve so that I can continue?

**Comment by riturajjain2000** [comment]
> Hey I am interested in doing this project. Can you approve so that I can continue?

Done!!

**Comment by OmKhare** [comment]
Okay thanks!
