### ISSUE TITLE
Add JavaScript

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#11]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by GowthamGoush** [comment]
May I work on this?

**Comment by icoderharshit** [comment]
@riturajjain2000 Can you assign this issue to me, if no one is working on this?

**Comment by shriya030** [comment]
Can I work on this issue if no one is working?

**Comment by icoderharshit** [comment]
@riturajjain2000 thank you for assigning this issue to me, I am almost on my way to make the PR for the same. @shriya030 , you may look to other issues or create one for yourself.

**Comment by shriya030** [comment]
@riturajjain2000 can I work now?

**Comment by icoderharshit** [comment]
@shriya030 I'm almost on my way to PR, was busy due to college exams. Incase, I face some conflicts while merging or fail to do the PR for this in the next two days...you may start working on the same issue. Hope you understand, @riturajjain2000

**Comment by shriya030** [comment]
> @shriya030 I'm almost on my way to PR, was busy due to college exams. Incase, I face some conflicts while merging or fail to do the PR for this in the next two days...you may start working on the same issue. Hope you understand, @riturajjain2000

It's okaayyyy! I'll find another issue for now.

**Comment by shonali2600** [comment]
@riturajjain2000 can I work on this?
