### ISSUE TITLE
Add AWS

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#146]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by nandini040** [comment]
I would like to work on this assign this to me.

**Comment by aj3011** [comment]
Can I work on this issue? @riturajjain2000

**Comment by saatviknagpal** [comment]
@riturajjain2000 Can I work on this??

**Comment by aj3011** [comment]
@riturajjain2000 I apologize for not being able to contribute on time. It's because my exams were going on since last 2 weeks. I will definitely find and work on other issues now.

**Comment by saatviknagpal** [comment]
> @riturajjain2000 I apologize for not being able to contribute on time. It's because my exams were going on since last 2 weeks. I will definitely find and work on other issues now.

Oh, I'm sorry for taking up the issue, if I knew you had exams then I wouldn't have taken it. But yeah you can work on another issues as I've already made a PR for this. 🙂
