### ISSUE TITLE
Add Machine Learning

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#157]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by pankaj892** [comment]
@riturajjain2000 do we need to add a ML section in readme for this issue ?

**Comment by riturajjain2000** [comment]
yes to readme and dictionary.json , both

**Comment by Subhangini** [comment]
would like to work on this issue

**Comment by pankaj892** [comment]
> yes to readme and dictionary.json , both

Ok @riturajjain2000 I would like to work on this

**Comment by riturajjain2000** [comment]
ITS ALREADY ASSIGNED

**Comment by Subhangini** [comment]
I was having my online viva due to which i was not able to work on this issue. Please consider this point and give me more time i will solve it as soon as posible.
Sorry for the delay
Thanks

**Comment by shriya030** [comment]
Can I work on this issue? @riturajjain2000

**Comment by ddvader44** [comment]
@Subhangini what's your progress in this issue?

**Comment by riturajjain2000** [comment]
> @Subhangini what's your progress in this issue?

No need to ask the participants , its already more than a week , reassign if they take more than a week on easy issues
