### ISSUE TITLE
Add MATLAB

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#18]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by Subhangini** [comment]
Would like to work on this assign to me.

**Comment by Subhangini** [comment]
Would like to work on this assign to me.

**Comment by Subhangini** [comment]
Would like to work on this assign to me.

**Comment by Subhangini** [comment]
I was having my online viva due to which i was not able to work on this issue. Please consider this point and give me more time i will solve it as soon as possible.
Sorry for the delay
Thanks
