### ISSUE TITLE
Add C

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#2]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by ojaswisharma16** [comment]
I want to contribute in it as a gssoc paricipant . plz assign it to me.
@riturajjain2000

**Comment by riturajjain2000** [comment]
Be sure to properly research about C !

**Comment by ojaswisharma16** [comment]
https://www.youtube.com/channel/UCBwmMxybNva6P_5VmxjzwqA

sir, i want to add this channel in  readme file under c++ (youtube channel) . But not able to change in the file .support required. @riturajjain2000

**Comment by ojaswisharma16** [comment]
Hello @riturajjain2000 

 I have added a new youtube channel for learning C++.
plz go through it and if you find it relevant, kindly merge it.

Thanks...

**Comment by riturajjain2000** [comment]
ok add that commit also , when you send PR for C

**Comment by hemant2705** [comment]
@ojaswisharma16   Are you still working upon it?
As its been 14 days 
if no ,I want to take it over.

**Comment by shriya030** [comment]
@riturajjain2000 Can I work on this issue?

**Comment by shriya030** [comment]
I'll do it by tomorrow or day after tomorrow. Sorry for the delay. My exams are going on.
