### ISSUE TITLE
Add .NET

### ISSUE THREAD

**Issue by ibhavikamalhotra** [CSwala/awesome-computer-science#220]
Resources for learning/knowing about .NET not yet published on this repository. I want to work on this issue under GSSoC'21, also add the required gssoc'21 labels. @riturajjain2000 .

**Comment by ddvader44** [comment]
go ahead @ibhavikamalhotra, make sure you research properly

**Comment by ibhavikamalhotra** [comment]
@riturajjain2000 I have made the required PR. #225 . Kindly see to it.
