### ISSUE TITLE
Add Linux 

### ISSUE THREAD

**Issue by ANSHIKA1806** [CSwala/awesome-computer-science#237]
@riturajjain2000 @ddvader44 
Resources of Linux have not been added to this repo. I would like to work on this issue.

**Comment by ANSHIKA1806** [comment]
@riturajjain2000 
Please assign this task to me.
Thank you

**Comment by ddvader44** [comment]
@ANSHIKA1806 go ahead, make sure you include many resources for linux!

**Comment by aj3011** [comment]
@riturajjain2000 Can I work on this issue ?

**Comment by aj3011** [comment]
If no one is working on this issue, can I work on this?
