### ISSUE TITLE
Add React.js

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#26]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by pranjalchaplot** [comment]
I want to work on this issue. Shall I fork the repo and start it??

**Comment by riturajjain2000** [comment]
> I want to work on this issue. Shall I fork the repo and start it??

Go ahead!!

**Comment by pranjalchaplot** [comment]
Now you can close this issue

**Comment by riturajjain2000** [comment]
Closed via #44
