### ISSUE TITLE
Add Mern Stack

### ISSUE THREAD

**Issue by Khushi-agarwal** [CSwala/awesome-computer-science#275]
I want to add mean stack which is a javascript stack. 
Please @ddvader44 @riturajjain2000 assign it to me.

**Comment by riturajjain2000** [comment]
The 4 components of it are already added to the list, what extra additions are you proposing?

**Comment by Khushi-agarwal** [comment]
> The 4 components of it are already added to the list, what extra additions are you proposing?

Since the four components of it are added separately,I wanted to create a one single head under which the resources of all are available.

**Comment by riturajjain2000** [comment]
Ok add this, but don't reuse links from those four, add new links specifically focused on their combined use as mern stack
