### ISSUE TITLE
Add Tcl

### ISSUE THREAD

**Issue by viralkumar28** [CSwala/awesome-computer-science#282]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by viralkumar28** [comment]
Assign me.

**Comment by riturajjain2000** [comment]
What is this tech , is this Transaction Control Language or anything else ?

**Comment by viralkumar28** [comment]
> What is this tech , is this Transaction Control Language or anything else ?

Tool Command Language
