### ISSUE TITLE
Fix the position of `Hibernate` in Dictionary.json file

### ISSUE THREAD

**Issue by noviicee** [CSwala/awesome-computer-science#302]
The current ordering of `Hibernate` in the Dictioanry.json file is not appropriate according to alphabetical order.
I would like to fix the ordering.

**Comment by riturajjain2000** [comment]
Not only hibernate , some other techs are also misplaced , so rearrange all of them

**Comment by noviicee** [comment]
Thanks @riturajjain2000 👍
