### ISSUE TITLE
Add Tensorflow

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#34]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by Komal-99** [comment]
I want to work over this issue , Kindly assign it to me,.
Please add Gssoc'21 label also

**Comment by riturajjain2000** [comment]
fix previous issues to get this assigned to you

**Comment by jonathanalvares9009** [comment]
Can you assign me this issue?
