### ISSUE TITLE
Add SQL

### ISSUE THREAD

**Issue by hemant2705** [CSwala/awesome-computer-science#343]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by hemant2705** [comment]
Assign this to me

**Comment by saatviknagpal** [comment]
Can I work on this @riturajjain2000 ?

**Comment by hemant2705** [comment]
I will soon complete it bro.. My exams were on that was the cause of delay

**Comment by saatviknagpal** [comment]
> I will soon complete it bro.. My exams were on that was the cause of delay

Oh okay, sure. No problem!

**Comment by shriya030** [comment]
@riturajjain2000 Can I work on this if no one is working?
