### ISSUE TITLE
Add Pandas

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#38]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by Komal-99** [comment]
Hi, I am Gssoc'21 participant]
I want to work over this issue. please assign this issue to me :)
Add Gssoc'21 label also

**Comment by riturajjain2000** [comment]
Can assign max 2 issues at a time to one person, plz fix existing issues first

**Comment by Komal-99** [comment]
ok👍

**Comment by Komal-99** [comment]
Please now assign this issue to me .

**Comment by riturajjain2000** [comment]
go ahead!
