### ISSUE TITLE
Add Flutter

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#4]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by GowthamGoush** [comment]
May I work on this?

**Comment by GowthamGoush** [comment]
Extremely sorry for the delay; I was swamped with exams. I make sure that I finish up by this weekend.

**Comment by ddvader44** [comment]
@GowthamGoush whats the progress

**Comment by shriya030** [comment]
@riturajjain2000 can I work on this issue?

**Comment by GowthamGoush** [comment]
> @GowthamGoush whats the progress

Oh, sorry again. I'll finish this by this Friday.
