### ISSUE TITLE
Add Play

### ISSUE THREAD

**Issue by noviicee** [CSwala/awesome-computer-science#408]
Play is a High Velocity Web Framework For Java and Scala.
I wish to add it's resources as a participant of GSSOC'21.

**Comment by ddvader44** [comment]
Its already done, sorry I didn't notice before.
Closing this

**Comment by noviicee** [comment]
Hey but it's not listed in the readme. That's why I opened a new one.
If you can provide me the link to the resource then that'll be helpful.
Thanks a lot 😄
