### ISSUE TITLE
Add WebRTC

### ISSUE THREAD

**Issue by shriya030** [CSwala/awesome-computer-science#465]
I want to add resources for WebRTC.

**Comment by Khushi-agarwal** [comment]
@riturajjain2000 can I work on this if no one is working.

**Comment by shriya030** [comment]
> @riturajjain2000 can I work on this if no one is working.

@Khushi-agarwal I am working already. I was busy, so wasn't able to do it.

**Comment by Khushi-agarwal** [comment]
> > @riturajjain2000 can I work on this if no one is working.
> 
> @Khushi-agarwal I am working already. I was busy, so wasn't able to do it.

@shriya030 I didn't know about it that you were working.
