### ISSUE TITLE
Add Photoshop

### ISSUE THREAD

**Issue by shriya030** [CSwala/awesome-computer-science#478]
I want to add resources to learn Photoshop. Please assign me this issue as a part of GSSOC'21.

**Comment by noviicee** [comment]
@riturajjain2000  @ddvader44  can I take this up if it's still open..?

**Comment by shriya030** [comment]
@noviicee I am already working on it :)

**Comment by noviicee** [comment]
@shriya030  no worries! good luck 👍 

> @noviicee I am already working on it :)

no worries! 👍

**Comment by noviicee** [comment]
> @noviicee I am already working on it :)

no worries! continue with your work 👍
