### ISSUE TITLE
Add Python

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#5]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by OmKhare** [comment]
Hey @riturajjain2000 I am a beginner and would like to contribute. I saw the README.md and I think I can help. Can you guide me through in this?.

**Comment by riturajjain2000** [comment]
> Hey @riturajjain2000 I am a beginner and would like to contribute. I saw the README.md and I think I can help. Can you guide me through in this?.

Sure !! you are required to add the resources that you used while learning python :)
