### ISSUE TITLE
Add Lua

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#51]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by fin1te** [comment]
Hey, I have just completed my work on this Issue, please assign me this so I can send a PR, thanks! :D

**Comment by riturajjain2000** [comment]
Make sure that you spend a good amount of time in research before making a PR !

**Comment by fin1te** [comment]
> Make sure that you spend a good amount of time in research before making a PR !

I just made a PR for all the topics I made data for last night, do check them and lmk if any changes / modification is necessary
