### ISSUE TITLE
Add Renorex

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#63]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by fin1te** [comment]
The Spelling is wrong I think, from what I see on Google, it's "Ranorex", do let me know If I'm wrong, thanks!

**Comment by fin1te** [comment]
Hey, I have just completed my work on this Issue, please assign me this so I can send a PR, thanks! :D
