### ISSUE TITLE
Add Lightworks

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#76]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by fin1te** [comment]
Hey, I have started working on this and will create a PR as soon as I'm assigned the issue, please assign me the issue so i can create a PR, thank you! ^_^

**Comment by fin1te** [comment]
Hey, I completed my work on this issue, do assign me the issue so I can raise the PR, thanks! ^_^
