### ISSUE TITLE
Add Metal

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#79]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by jonathanalvares9009** [comment]
Can you assign me this issue?

**Comment by jonathanalvares9009** [comment]
@riturajjain2000 can you please tell me more about metal?

**Comment by riturajjain2000** [comment]
Its a GRAPHIC API from apple , see-https://en.wikipedia.org/wiki/Metal_(API)
