### ISSUE TITLE
Add Competitive Programming

### ISSUE THREAD

**Issue by JayantGoel001** [CSwala/awesome-computer-science#8]
I want to completive programming material.
1. Different Website to learn .
2. Different Website to code the stuff.
3. Different links of Books.

**Comment by riturajjain2000** [comment]
> I want to completive programming material.
> 
> 1. Different Website to learn .
> 2. Different Website to code the stuff.
> 3. Different links of Books.

Go ahead @JayantGoel001  , but remember to follow the pattern

**Comment by JayantGoel001** [comment]
@riturajjain2000 Which Pattern? Did you mean contribution guidelines?
