### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by riturajjain2000** [CSwala/awesome-computer-science#91]
See `Android` in README.md to get an idea of the contents of the PR for this issue.

**Comment by namitgpta** [comment]
I would like to work on this. Please assign to me. Thanks !!

**Comment by riturajjain2000** [comment]
Go ahead!

**Comment by namitgpta** [comment]
Can I get GSSOC'21 batch for this issue

**Comment by namitgpta** [comment]
Thnx a lot!!
